name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files in repository
      run: ls -la

    - name: Verify README exists
      run: |
        if [ -f "README.md" ]; then
          echo "README.md exists."
        else
          echo "README.md does not exist." && exit 1
        fi
